### ISSUE TITLE
Implement a data resampler for optimise

### ISSUE THREAD

**Issue by KLohse** [DRL/gIMble#10]
Implement a data resampler

It would be nice/useful to be able to sample from the observed global bSFS. Ideally this info should be used to decide on the stopping condition for ftol_rel

- [ ] if it is fast to resample 100 datasets (the same # of blocks as the real data) from the empricial bSFS/block_Total it would be super useful to do this as part of (and at the beginning) of optimise. 2SD of lnCL across resampled datasets could then be used as non-arbitrary default value for ftol_rel: once this threshold is reached in the optimisation we know that we're within sampling noise. 

Stuff to think about:
- This is conservative (perhaps too conservative) because it assumes that blocks are independent. 
- It would be good to print all stopping conditions to screen for the user and make the exitcode more human readable, i.e. say what max iterations is.

**Comment by KLohse** [comment]
@GertjanBisschop. I realized that one can save a lot of compute time by resampling much smaller datasets from the observed bSFS:

Say the real dataset is big and consists of 100 000 000 blocks (like the Heli test data), we can resampled datasets that consist of only 1000 blocks. The expected SD in lnCL across these mini datasets is SD_mini * sqrt[n_mini/n_full] . I am not sure whether this still works in the limit, i.e. samples of a single block but it somehow has to ...

**Comment by GertjanBisschop** [comment]
Solved by #34
