### ISSUE TITLE
makegrid

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#14]
- [x] `makegrid` should error if populations in INI are not in gstore

**Comment by GertjanBisschop** [comment]
perhaps throwing a warning is better. Again, what if someone wants to make a grid without having any data. Or is there a way to set up the gstore without data, yet still specify populations?

**Comment by DRL** [comment]
this was meant for when INI contains
```
A = 'my_pop_1'
B = 'another_pop'
```
and then the data in the Gstore is for `my_pop_1` and `another_different_pop`. 

If there is no data nothing needs to be done, but it should error if they are set to different pops.
