### ISSUE TITLE
Compare ETP/bsfs-tensors with numpy.float64 against sage.expressions 

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#17]
- [ ] numpy multiplication possible with sage.expression (i.e. objects)?
- [ ] write Tensor SuperClass to overload multiplication method to make it work?

**Comment by GertjanBisschop** [comment]
Currently the way we deal with machine precision is as follows:
ETPs are stored as `sagemath.all.RealField(prec=165)` (+/- 50 digits precision). Once the marginal probabilities are calculated the ETPs matrix is converted to `np.float64`  (which is equal to `sagemath.all.RealField(prec=53)`).

Adaptation of the code would be necessary to do all operations on the ETP matrices correctly and efficiently (example. `np.log`).

Secondly, how are we using the precision specified in the ini file. Currently standard 25. We should be able to warn the user that when and if ETPs evaluate incorrectly (not in [0,1]) to increase machine precision using the ini file. This will be useful for people using large kmax values.

See commit 16b357c470172d124b3a68c028f97db5224fd2ef
