### ISSUE TITLE
Tweak onscreen and bed output for gridsearch

### ISSUE THREAD

**Issue by KLohse** [DRL/gIMble#31]
It is important to clearly distinguish between inferred parameters and parameters that were fixed/specified by the user at all times:

- get rid of mu column in the .bed fille generate by gridserach (this is a use-specified scalar which is not part of the inference)
- give the .ini file which specifies the grid used in the search in the hearder of the .bed file
- ideally only parameters that are part of the grid should be columns in the .bed file, i.e. there is no need to list synced N_e parameters or globally fixed parameter (e.g. T) in the .bed file. While including this info is not costly computationally it is likely to confuse users.

**Comment by DRL** [comment]
- we just have to figure out which are the params-to-plot ... should probably be decided when making the grid?

**Comment by DRL** [comment]
done
