### ISSUE TITLE
conflicting ini and model file

### ISSUE THREAD

**Issue by GertjanBisschop** [DRL/gIMble#32]
There is currently no step that checks whether all equation parameters have a numeric value associated with them to be substituted in `calculate_inverse_laplace()`. I can for example specify a model with migration, and combine that with an ini file without migration. All equations will be built, and the inverse laplace can even be calculated be it with M_A_B still as a symbol. The script will error once numerical evaluation is requested.

**Comment by DRL** [comment]
New module `makemodel` now writes INI files that point to the model they are based on (in `models/`).

Validating of params for model still has to be implemented in `parameterObj._parse_config()` (`parameterObj._validate_config()` ?) ...

**Comment by GertjanBisschop** [comment]
Right, but we have to make sure that we are still able to for run a model without a split on an ini file with a split. However, the other way round should be caught early on.

**Comment by DRL** [comment]
Good point. Happy to have a small meeting on thursday or friday to compare notes.
