### ISSUE TITLE
Output bed file to build recombination map with

### ISSUE THREAD

**Issue by GertjanBisschop** [DRL/gIMble#33]
Use `query` to spit out a csv with:
    `names=['chrom', 'windowStart', 'windowEnd']` 
which can be used by user to adapt their own recombination map to the format that `gimble` needs.

**Comment by DRL** [comment]
Not sure i understand.

what coordinates should that file have? the ones of windows?

**Comment by GertjanBisschop** [comment]
yes, sorry, not chromStart and End but windowStart and End indeed. This is the file we can that then should be used to make recombination bins to simulate windows with.

**Comment by DRL** [comment]
technically that already exists:

`./gimble query -z store.z --bed -w` 

should make a bed file of windows ...

**Comment by GertjanBisschop** [comment]
Yes fantastic! Does what is should do. User should be able to extract the first columns and add a recombination rate value for each. 
All issues should be resolved like this!

**Comment by KLohse** [comment]
Yup, just being able to output the win coords with query would be useful.
