### ISSUE TITLE
Log results during optimisation of sims

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [DRL/gIMble#39]
Currently optimisation writes `.csv` and `_summary.csv` files once all sim replicates have been optimised. One can imagine a scenario where optimisation of a replicate 'fails', e.g. when the maximum likelihood parameter set includes parameter values at the upper or lower bounds specified in the `.ini` file.

I would suggest writing the result of each replicate to a log file as soon as they finish rather than once all replicates are done. This way problems can be seen early on in optimisation and the job can be killed and restarted with a modified `.ini.` file.

**Comment by GertjanBisschop** [comment]
solved by #dc174c0fc8449d17b50ce2425b9532f26ede6368

**Comment by GertjanBisschop** [comment]
checking potential issues with logging to same file during optimization when using `concurrent.futures` pooling.
