### ISSUE TITLE
optimize output

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#42]
- parameters should be scaled when printed
- it would be great to show both the unscaled and scaled paras, i.e. something like before `[{'lnCL': -358538174.83039397, 'optimum': {'Ne_A': 1569024.4592187495, 'Ne_A_B': 556156.5701562501, 'me_B_A': 7.121940243735859e-07, 'T': 6424351.374492935}, 'exitcode': 'max number of evaluations reached'}]`

**Comment by GertjanBisschop** [comment]
currently parameters are printed to screen in coalescent time scales: [`all_rates`](https://github.com/DRL/gIMble/blob/dc174c0fc8449d17b50ce2425b9532f26ede6368/lib/math.py#L205). Everything is in place to print unscaled parameters as well: `all_rates_unscaled`.

**Comment by GertjanBisschop** [comment]
see #63
