### ISSUE TITLE
changes to simulate with new config

### ISSUE THREAD

**Issue by GertjanBisschop** [DRL/gIMble#69]
- [x] make base case work again
- [x] sim winning combo for each window with fixed rec rate
- [x] sim winning combo for each window with rec map
- [x] change `--grid` flag in simulate to windowwise-bootstrap
- [x] adapt `requirements.txt`

**Comment by GertjanBisschop** [comment]
Step 2 and 3 (window-wise parametric bootstrap) require:

- [ ] using labels instead of hashes to identify grids (@dombadom)

**Comment by DRL** [comment]
dealt with in latest release
