### ISSUE TITLE
preprocess can't handle directory prefixes for temp folder

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#73]
probably an issue with strings vs pathlib-objects.

```
[X] (STDERR): '/bin/sh: 1: cannot create .tmp_gimble_759l7ql7/4_gimble_preprocess/drosophila_mojavensis.SCO5.20210603.preprocess.multi_callable.bed: Directory nonexistent\nError: Only a single file was specified. Nothing to combine, exiting.' 
```

**Comment by aaannaw** [comment]
Hello, Professor
I suffered from the similar error and how to solve. Could you give me any suggestions.
[X] => bcftools filter --threads 10 -Oz -S . -e '(FMT/DP[0]<8 | FMT/DP[0]>45) | (FMT/DP[1]<8 | FMT/DP[1]>51) | (FMT/DP[2]<8 | FMT/DP[2]>48) | (FMT/DP[3]<8 | FMT/DP[3]>48) | (FMT/DP[4]<8 | FMT/DP[4]>57) | (FMT/DP[5]<8 | FMT/DP[5]>57) | (FMT/DP[6]<8 | FMT/DP[6]>66) | (FMT/DP[7]<8 | FMT/DP[7]>78) | (FMT/DP[8]<8 | FMT/DP[8]>51) | (FMT/DP[9]<8 | FMT/DP[9]>66) | (FMT/DP[10]<8 | FMT/DP[10]>51) | (FMT/DP[11]<8 | FMT/DP[11]>54) | (FMT/DP[12]<8 | FMT/DP[12]>54) | (FMT/DP[13]<8 | FMT/DP[13]>48) | (FMT/DP[14]<8 | FMT/DP[14]>51) | (FMT/DP[15]<8 | FMT/DP[15]>51) | (FMT/DP[16]<8 | FMT/DP[16]>54) | (FMT/DP[17]<8 | FMT/DP[17]>51) | (FMT/DP[18]<8 | FMT/DP[18]>54) | (FMT/DP[19]<8 | FMT/DP[19]>72) | (FMT/DP[20]<8 | FMT/DP[20]>51) | (FMT/DP[21]<8 | FMT/DP[21]>156) | (FMT/DP[22]<8 | FMT/DP[22]>63) | (FMT/DP[23]<8 | FMT/DP[23]>66) | (FMT/DP[24]<8 | FMT/DP[24]>51) | (FMT/DP[25]<8 | FMT/DP[25]>63)' .tmp_gimble_dmrogmhv/vcf.filtered.pass.vcf.gz | bcftools sort -T .tmp_gimble_dmrogmhv/vcf.filtered.vcf.gz.sort.tmp -Oz > 02.gimble.proprecess.vcf.gz && bcftools index -t 02.gimble.proprecess.vcf.gz
[X] (STDERR): 'Writing to .tmp_gimble_dmrogmhv/vcf.filtered.vcf.gz.sort.tmp\n[E::hts_open_format] Failed to open file .tmp_gimble_dmrogmhv/vcf.filtered.vcf.gz.sort.tmp/00001.bcf\nCannot write .tmp_gimble_dmrogmhv/vcf.filtered.vcf.gz.sort.tmp/00001.bcf: No such file or directory'
