### ISSUE TITLE
Problems with sync'ing populations 

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#74]
Use of `C_s`as sync'ed coalescence rate ... not sure what is easier. 

```
coalescence_rates = [sage.all.var(rate) for rate in ['C_A', 'C_B', 'C_A_B']]
vs 
coalescence_rates = [sage.all.var(rate) for rate in ['C_A', 'C_s', 'C_s']]
```

**Comment by GertjanBisschop** [comment]
Won't `'C_s'` cause problems as soon as we have more coalescence rates to sync. Our initial solution was to sync to one of the populations, so `['C_A', 'C_B', 'C_B']` (first pop, depending on the order). This way no matter how many populations we have, we always know how to sync them.
