### ISSUE TITLE
Query the probabilities of mutuples for a given model and parameters

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [DRL/gIMble#79]
Feature request:

It would be useful to be able to get the probabilities of mutuples for a given model and parameter values. These could then be compared to the frequency of mutuples in the data. See Fig 3 of https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1517-y for an example of the kind of diagnostic plots that could be generated from these data.

**Comment by DRL** [comment]
some ideas
- decouple data wrangling from output
- new module named... ?
- saved as expectations? residuals?
- based on optimize (single value), makegrid (range) config?
- query to output as csv with header naming config, params, etc

**Comment by DRL** [comment]
See `query`
