### ISSUE TITLE
Terminated during Infering coverage levels from BAM files

### ISSUE THREAD

**Issue by aaannaw** [DRL/gIMble#80]
Hello, Professor
I am running "gIMble process" procedure. However I always suffer from the error： 
![image](https://user-images.githubusercontent.com/109299053/224588693-97d5fe88-9997-4b84-99f4-e152a6eac8d4.png)
I have 26  bam files (except ref sample) and my vcf file has all sites, include variants and invariants. My command is "gIMble preprocess -f Ma6.Chr.2210.fasta -b 00.bam_dir -v 04.merge.vcf.gz -t 20 -o 01.gimble".
Maybe I should generate ref sample bam file by aligning ref sample fastq file with ref fasta and put  in bam_dir？Could you give me any suggestions？ Thanks very much.
Looking forward with your reply！

**Comment by DRL** [comment]
Hi aaannaw,

this looks like your slurm job got killed by the system.

This is probably not a gimble issue so I will close this.
