### ISSUE TITLE
Can the input file vcf(SNP) only be generated with freebayes?

### ISSUE THREAD

**Issue by kuangzhuoran** [DRL/gIMble#81]
I met this error: "the tag 'RPL' is not defined in the VCF header";

I didn't find out how to use gatk to generate this tag

**Comment by DRL** [comment]
Hi kuangzhuoran,

yes, so far we only support freebayes' VCFs. 

If you can post header (+ 10 variant rows) of your VCF file then I can try to add support for your type of VCF file.

cheers, 

dom

**Comment by DRL** [comment]
Not sure whether this is still relevant but `preprocess` should now work even when "balance" TAGs are not present in VCF.
