### ISSUE TITLE
Preprocess step occurs error 

### ISSUE THREAD

**Issue by aaannaw** [DRL/gIMble#83]
Hello,Professor
I am running the gimble preprocess  step, but I met the error log in the following log file. 
Could you give me any suggestions!
[log.txt](https://github.com/DRL/gIMble/files/11328915/log.txt)

**Comment by DRL** [comment]
It seems like `gimble preprocess` can't write to the temporary folder it created when it started.

Could it maybe be 
- that the folder is maybe deleted if the job takes too long?
- that there is not enough space?

The last command that gets written to the log is the one it tries to run and failed. 

So try to run that command manually and try to figure out why it failed.
