### ISSUE TITLE
Could you write a shell scripts for preprocess step1 and do not write files into .tmp folder?

### ISSUE THREAD

**Issue by gotouerina** [DRL/gIMble#85]
I have run gimble v1.01 and v1.02(maybe). I think the functions of preprocess step is not complete.

Could you provide a shell script for preprocess ? It will be easy to seperate each step for work. For example, now I can only preprocess vcf, bam, and fasta only in one step. When this step occured error, I can only check errors and run again...This will lead to a big waste of time and memory, and I can not use parellel and parafly to accelerate its run. I also suggest you rename the output folder from .tmp  to tmp/. Now if this step is not complete,  I can hardly find files because they are in hidden folder.

**Comment by DRL** [comment]
The problem with the preprocess step is that the output files of the different steps determine the following steps. So doing this in bash is even more of a nightmare than it is doing it in python...

If you have problems – which might be due to file formats or resources – i would recommend that you first run one chromosome with a two BAM files, that way you can check that everything works correctly before running the whole dataset.

**Comment by gotouerina** [comment]
I run this step again with 2 bams.
It reports
[+] Parsing BAM files...[%] Infer coverage levels from BAM files...:  50%|??????????         | 1/2 [07:25<07:25, 445.40s/it]
[%] Infer coverage levels from BAM files...: 100%|???????????????????| 2/2 [12:14<00:00, 367.40s/it]                                                                                          
[X] Duplicated sample IDs detected. Please provide only one BAM file per sample ID.
[X]      SM:PL:illumina in kem0.sort.markdup.bam
[X]      SM:PL:illumina in rus0.sort.markdup.bam
I review my alignment command , it is
bwa mem -t 30 -R "@RG\tID:${samplename}\tPL:illumina\tLB:${samplename}\tSM:${samplename}" $ref ${samplename}_clean_1.fq.gz ${samplename}_clean_2.fq.gz
So what's wrong with it and what should I do ?

**Comment by gotouerina** [comment]
> I run this step again with 2 bams. It reports [+] Parsing BAM files...[%] Infer coverage levels from BAM files...: 50%|?????????? | 1/2 [07:25<07:25, 445.40s/it] [%] Infer coverage levels from BAM files...: 100%|???????????????????| 2/2 [12:14<00:00, 367.40s/it] [X] Duplicated sample IDs detected. Please provide only one BAM file per sample ID. [X] SM:PL:illumina in kem0.sort.markdup.bam [X] SM:PL:illumina in rus0.sort.markdup.bam I review my alignment command , it is bwa mem -t 30 -R "@rg\tID:${samplename}\tPL:illumina\tLB:${samplename}\tSM:${samplename}" ref{samplename}_clean_1.fq.gz ${samplename}_clean_2.fq.gz So what's wrong with it and what should I do ?

After that,I use only one bam to do it
report:

[+] Running 'gimble preprocess'...
[+] Parsing FASTA file...
[+]     => Wrote 'gimble.genomefile'
[+] Parsing BAM files...
[%] Infer coverage levels from BAM files...:   0%|                            | 0/1 [00:00<?, ?it/s][W::hts_idx_load3] The index file is older than the data file: /data/01/user214/acomysvcf/11.gimble/bamtest/rus0.sort.markdup.bai
[%] Infer coverage levels from BAM files...: 100%|███████████████████| 1/1 [04:38<00:00, 278.38s/it]                                                                                          
[=] =====================================================================
                bam_f   sample_id  cov_mean  cov_sd  depth_min  depth_max
rus0.sort.markdup.bam PL:illumina      5.01  276.06          8         10
[=] =====================================================================
[+]     => Wrote 'gimble.coverage_summary.csv'[+] Infer callable regions...
[%] Inferring callable regions...: 100%|█████████████████████████████| 1/1 [04:05<00:00, 245.69s/it]                                                                                          
[X] Sample ID mismatch
[X] Sample IDs in readgroups of BAM files : PL:illumina
[X] Sample names in VCF file : ca12, ca13, ca14, ca15, ca16, ca81, ca91, ca92, kem0, kem1, kem4, kem5, kem6, kem7, kem8, kem9, per0, per1, per2, per3, per4, per5, per8, per9, rus0, rus1, rus4, rus5, rus6, rus7, rus8, rus9

I can not understand why this program regard PL:illumina as my input file name. Could you tell me how can I deal with this problem?

**Comment by gotouerina** [comment]
Although you recommand that use one chromosome files and two bams to do it, it is surprisingly that if the number and name of BAM format files  is not cosistent with the VCF format file, the program will run error.

**Comment by DRL** [comment]
Can you post the output of 

```samtools view -H rus0.sort.markdup.bam```

> Although you recommand that use one chromosome file and two bams to do it, it is surprisingly that if the number and name of BAM format files is not cosistent with the VCF format file, the program will run error.

You should have subsetted the VCF file for chromosome and samples. 

> I have used lots of software that detect migration rate or gene flow, such as Dsuite, treemix, Dfoil. They all used "poplist" to distinguish different group of species. I do not know why you try to identify it in BAM format file... Of course, it is only complaint, you can neglect it.

If the other software make you happier, you should use the other software... 😄 

The need for figuring out samples in `gIMble preprocess` is due to the fact that for each sample both variant and invariant sites need to be quantified so that the later blocks can be accurately constructed. The other software do not do that.

**Comment by gotouerina** [comment]
> Can you post the output of
> 
> `samtools view -H rus0.sort.markdup.bam`
> 
> > Although you recommand that use one chromosome file and two bams to do it, it is surprisingly that if the number and name of BAM format files is not cosistent with the VCF format file, the program will run error.
> 
> You should have subsetted the VCF file for chromosome and samples.
> 
> > I have used lots of software that detect migration rate or gene flow, such as Dsuite, treemix, Dfoil. They all used "poplist" to distinguish different group of species. I do not know why you try to identify it in BAM format file... Of course, it is only complaint, you can neglect it.
> 
> If the other software make you happier, you should use the other software... 😄
> 
> The need for figuring out samples in `gIMble preprocess` is due to the fact that for each sample both variant and invariant sites need to be quantified so that later blocks can be accurately constructed. The other software do not do that.

Here are results of  samtools view -H rus0.sort.markdup.bam

@HD	VN:1.6	SO:coordinate
@SQ	SN:LG01	LN:213430649
@SQ	SN:LG02	LN:161638945
@SQ	SN:LG03	LN:151808714
@SQ	SN:LG04	LN:149750782
@SQ	SN:LG05	LN:147180119
@SQ	SN:LG06	LN:135198006
@SQ	SN:LG07	LN:130413935
@SQ	SN:LG08	LN:128545730
@SQ	SN:LG09	LN:127068021
@SQ	SN:LG10	LN:125439249
@SQ	SN:LG11	LN:122489963
@SQ	SN:LG12	LN:121900037
@SQ	SN:LG13	LN:117710310
@SQ	SN:LG14	LN:101629228
@SQ	SN:LG15	LN:97350281
@SQ	SN:LG16	LN:87318440
@SQ	SN:LG17	LN:80503342
@SQ	SN:LG18	LN:40400000
@SQ	SN:LG19	LN:26176828
@SQ	SN:Contig1	LN:936674
@SQ	SN:Contig2	LN:560345
@SQ	SN:Contig3	LN:476099
@SQ	SN:Contig4	LN:467341
@SQ	SN:Contig5	LN:376264
@SQ	SN:Contig6	LN:372079
@SQ	SN:Contig7	LN:358041
@SQ	SN:Contig8	LN:295478
@SQ	SN:Contig9	LN:265517
@SQ	SN:Contig10	LN:244039
@SQ	SN:Contig11	LN:200000
@SQ	SN:Contig12	LN:115602
@SQ	SN:Contig13	LN:106596
@SQ	SN:Contig14	LN:61208
@SQ	SN:Contig15	LN:58444
@RG	ID:rus0	PL:illumina	LB:rus0	SM:rus0
@PG	ID:bwa	PN:bwa	VN:0.7.17-r1188	CL:bwa mem -t 30 -R @RG\tID:rus0\tPL:illumina\tLB:rus0\tSM:rus0 cahirinus.fa CleanFastq/rus0_clean_1.fq.gz CleanFastq/rus0_clean_2.fq.gz
@PG	ID:samtools	PN:samtools	PP:bwa	VN:1.12	CL:samtools view -b -S rus0.sam
@PG	ID:samtools.1	PN:samtools	PP:samtools	VN:1.12	CL:samtools sort -@ 2 -m 10G -o rus.sort.bam rus0.sam.bam
@PG	ID:MarkDuplicates	VN:2.25.1	CL:MarkDuplicates INPUT=[BamOut/rus0.sorted.bam] OUTPUT=BamOut/rus0.sort.markdup.bam METRICS_FILE=BamOut/rus0.marked_dup_metrics.txt REMOVE_DUPLICATES=true CREATE_INDEX=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true DUPLEX_UMI=false ADD_PG_TAG_TO_READS=true ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false	PN:MarkDuplicates
@PG	ID:samtools.2	PN:samtools	PP:samtools.1	VN:1.17	CL:samtools view -H rus0.sort.markdup.bam

**Comment by DRL** [comment]
I changed how the sample ID is parsed from the BAM. It should work now.

**Comment by DRL** [comment]
make sure you use the latest version
