### ISSUE TITLE
An optimization in index identification

### ISSUE THREAD

**Issue by gotouerina** [DRL/gIMble#88]
I work in /data/01/user214/acomysvcf/11.gimble , I link ca.fa from /data/00/user/user152/ac.genome/. But in /data/01/user214/acomysvcf/11.gimble, I have created index file ca.fa.fai

It reports
[X] (STDERR): '[E::fai_build3_core] Failed to open FASTA index /data/00/user/user152/ac.genome/ca.fa.fai : Permission denied\nFailed to load the fai index: /data/00/user/user152/ac.genome/ca.fa\nFailed to read from standard input: unknown file type\nFailed to read from standard input: unknown file type\nFailed to read from standard input: unknown file type\nFailed to read from standard input: unknown file type'

**Comment by DRL** [comment]
It seems that many of your errors seem to be caused by you not being able to write/access part of your file system. 

Are you sure that gimble can write to and read from the parts of the filesystem you specify?

**Comment by gotouerina** [comment]
But what you guess is true, it is caused by permission. This quesion can be not vital but I think can be an optimization

**Comment by DRL** [comment]
Index files need to be in the same folder as the files they index.
