### ISSUE TITLE
One chromesome test failed, I really suggest  split preprocess step of VCF, BAM, and FASTA into individual step

### ISSUE THREAD

**Issue by gotouerina** [DRL/gIMble#89]
I use only SNPs of one-chr, and reports
[+] Running 'gimble preprocess'...
[+] Parsing FASTA file...
[+]     => Wrote 'gimble.genomefile'
[+] Parsing BAM files...
[%] Infer coverage levels from BAM files...:  50%|█████████▌         | 1/2 [06:46<06:46, 406.43s/it][W::hts_idx_load3] The index file is older than the data file: /data/01/user214/acomysvcf/11.gimble/bamtest/rus0.sort.markdup.bai
[%] Infer coverage levels from BAM files...: 100%|███████████████████| 2/2 [11:09<00:00, 334.55s/it]                                                                                          
[=] ===================================================================
                bam_f sample_id  cov_mean  cov_sd  depth_min  depth_max
kem0.sort.markdup.bam      kem0      8.14   56.28          8         16
rus0.sort.markdup.bam      rus0      5.01  276.06          8         10
[=] ===================================================================
[+]     => Wrote 'gimble.coverage_summary.csv'
[+] Infer callable regions...
[%] Inferring callable regions...: 100%|█████████████████████████████| 2/2 [09:00<00:00, 270.04s/it]                                                                                          
[+]     => Wrote 'gimble.samples.csv'
[+] Process variants (this might take a while)...
[+] Filtering VCF file ...
[-] '/data/01/user214/acomysvcf/11.gimble/LG01.recode.vcf.gz' is not a freebayes VCF. BALANCE filter (-e 'RPL<1 | RPR<1 | SAF<1 | SAR<1') will not be applied.                                
[+] Subsetting VCF file ...
[+] Adjusting callable regions (Filter FAILs are removed)...
[+]      => Wrote 'gimble.bed' ...
[+] Adjust genotypes in uncallable regions...
[X] The command following command failed with error code 255:
[X] => bcftools filter --threads 1 -Oz -S . -e '(FMT/DP[0]<8 | FMT/DP[0]>16) | (FMT/DP[1]<8 | FMT/DP[1]>10)' tmp_gimble_15zusgyi/vcf.filtered.pass.vcf.gz | bcftools sort -T tmp_gimble_15zusgyi/vcf.filtered.vcf.gz.sort.tmp -Oz > gimble.vcf.gz && bcftools index -t gimble.vcf.gz
[X] (STDERR): 'Writing to tmp_gimble_15zusgyi/vcf.filtered.vcf.gz.sort.tmpom7pM6\n[E::bcf_hdr_read] Input is not detected as bcf or vcf format\nCould not read VCF/BCF headers from -\nCleaning'

I check the output file and find that vcf.filtered.pass.vcf.gz only contained header but no SNPs. I think it is a paradox that, if I use a small sample to test, the filter is too strict that I  can not analysis. But when we test a big sample, it consumes too much. Addtionally, , I really suggest  split preprocess step of VCF, BAM, and FASTA into individual......The preprocess.py itself is a nightmare.

**Comment by gotouerina** [comment]
I change a bigger vcf file, now it can run through.

**Comment by gotouerina** [comment]
I read your preprocess,py again, I think threre are some steps can be updated easily:
1. Genome file can be set optional but not necessary. I see "samtools dict {parameterObj.fasta_file} | grep '^@SQ' | cut -f2-3 | perl -lpe 's/SN:|LN://g" is used in your script and it is not fast as " bioawk -c fastx '{print $name,length($seq)}' *.fa && samtools faix *.fa" etc,,

2 Read bam from a dictionary may be a good idea, but I think read from bamlist.txt may be better. Always move bam or rm and relink bam is not suitable as modify a config file.

3.All of above....What I want is a "resume from break-point" mechanism, I think it should not be hard to complete...

**Comment by DRL** [comment]
Will submit those as separate issues and close this one.
