### ISSUE TITLE
Add lnCL for the centre to gridsearch default .tsv output

### ISSUE THREAD

**Issue by KLohse** [DRL/gIMble#9]
The centre of the grid is special, i.e. it makes sense to assume that it correspond to some global model. So an obvious question when running gridsearch over windows is how much better the local MCLE (the best fitting point of the grid for a win) is compared to the global model/centre.

- [x] Add an extra lnCL column to the default .tsv file gridsearch returns for the lnCL for the centre

Stuff to think about:
- Do we need to record the centre of the grid in the .tsv (extra columns make no sense, but perhaps the file name) or does that info exist in the zar store?
- It would be useful to make gridsearch work for sim replicates in exactly the same way as for windows.

**Comment by DRL** [comment]
Added column with `(max(lnCLs) - lnCLs_center)` in the TSV output of `gridsearch`.

Reopen if something else is desired.
