### ISSUE TITLE
gimble query error

### ISSUE THREAD

**Issue by gotouerina** [DRL/gIMble#92]
I have finished gimble simulate, and want to check the results. I use ./gIMble/gimble  query -z analysis.z -l label

It reports:
[+] Running 'gimble query' ...
[X] Label 'label' not found in store. Available labels:
[#] parse
        - blocks
        - windows
[#] gridsearch
        - gridsearch/windows_kmax2/IM_BA_grid
[#] makegrid
        - makegrid/IM_BA_grid
[#] optimize
        - optimize/windows_kmax2.windowsum/IM_BA_optimize
[#] simulate
        - simulate/IM_BA_grid
[#] tally
        - tally/blocks_kmax2
        - tally/windows_kmax2

So I use this fuction to print results of parse gridsearch makegrid  optimize and tally like "./gIMble/gimble  query -z analysis.z -l gridsearch/windows_kmax2/IM_BA_grid". It run correctly.
But when I run "./gIMble/gimble  query -z analysis.z -l simulate/IM_BA_grid", It reports

.[+] Running 'gimble query' ...
[X] 'simulate/IM_BA_grid' does not point to a tally.

I do not know what happened and are checking about it.

**Comment by gotouerina** [comment]
gridsearch result was used to simulate.
my command line 

./gimble simulate -z analysis.z \
    --seed 19 --replicates 100 --windows 289 --blocks 500 \
    --block_length 64 -a 2 -b 2 \
    --gridsearch_key gridsearch/windows_kmax2/IM_BA_grid \
    -k 2,2,2,2 -s IM_BA_grid -p 55 -u 5e-9

**Comment by gotouerina** [comment]
Maybe query is not designed for simulate check ?
Your manual did not say it.

**Comment by DRL** [comment]
If you want to query the tallies you need to specify which replicate you want.

For getting the 0-th replicate you need to run:
```
./gIMble/gimble query -z analysis.z -l simulate/IM_BA_grid/0
```
