### ISSUE TITLE
Do block region overlap?

### ISSUE THREAD

**Issue by gotouerina** [DRL/gIMble#95]
I find region overlap in result of gridresearch 

\# sequence      start   end     window_idx      Ne_A    Ne_A_B  Ne_B    T       me      lnCl
LG01    58723052        78676714        10      200000.0        100000.0        100000.0        4256034.0       2.21e-06        -198.88452883659582
LG01    64338639        85660677        11      200000.0        100000.0        100000.0        4256034.0       2.21e-06        -214.78991351234944
LG01    67157490        92000983        12      200000.0        100000.0        100000.0        4256034.0       2.21e-06        -225.56328172613942

Is it correctly when you design your software?

**Comment by DRL** [comment]
That depends on how you construct the windows with `windows`.

If you specified sliding windows with the step-size, then they will overlap by that step-size.
